name: vikash_technical_hub_app
description: Master Autonomous IT Agency Command Center for Vikash Technical Hub.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0